version: "3"
services:
       toj-app:
           container_name: toj-app
           image: toj/tojapp:1.2
           restart: always
           build: .
           ports:
             - "8080:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'